collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#91413A'
    - '#FBA291'
    - '#C76D5C'
    - '#4C271E'
    - '#FBE1CF'
  rhythmicContrast: 1
typography_spectrum: 0.3936679
layout_spectrum: 0.9862604
name: June LaPointe.com
